### ISSUE TITLE
fter the new version update, the left screen content cannot be clicked after the sidebar is collapsed, and there is no response

### ISSUE THREAD

**Issue by sevenlucas7** [Nuked88/ComfyUI-N-Sidebar#34] opened 2024-04-22 06:32 UTC
After the new version update today, local language search is supported again, which is great. But I found a new problem. After the new version update, the left screen content cannot be clicked after the sidebar is collapsed, and there is no response.

**Comment by alessandroperilli** [comment] 2024-04-22 08:29
I'm not certain my problem is the same problem described by @sevenlucas7, but this is what I see now:

<img width="586" alt="Screenshot 2024-04-22 at 09 26 01" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/9775949/552381ec-e296-449e-b33a-201a3051a8a0">

There is no way for me to expand the sidebar anymore. It's basically inaccessible other then the UI element in the screenshot.

When I press the Burger icon, it shows what it seems a failed attempt to create the search box:

<img width="54" alt="Screenshot 2024-04-22 at 09 28 03" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/9775949/0f609717-8ade-4aea-9b59-45376ebcdc90">

The other two icons do nothing.


Thanks for looking into this.

**Comment by Nuked88** [comment] 2024-04-22 21:54
ok about the @sevenlucas7  problem, should be fixed right now. 
About @alessandroperilli  can you try to delete settings.json (backup it first) in the App folder, reboot comfyui and change browser to see if the problem is still present?
If is not i think that you shoud do a factory reset of the sidebar settings in Vivaldi and then restore manually the backupped settings.json , then reboot comfyui.
Let me know if it's working!

**Comment by sevenlucas7** [comment] 2024-04-22 23:18
The issue has been resolved, thanks for your effort, @Nuked88

**Comment by alessandroperilli** [comment] 2024-04-23 08:11
Given that @sevenlucas7 solved his problem, and mine doesn't seem related, I'll open a dedicated issue about this and this one can be closed. Sorry for hijacking it. I thought they were the same thing.

**Closed as completed** 2024-04-23 19:20 UTC
