### ISSUE TITLE
How to roll back to the previous version? 

### ISSUE THREAD

**Issue by VAVAVAAA** [Nuked88/ComfyUI-N-Sidebar#105] opened 2024-08-06 02:32 UTC
I used Update All on manager, but today I found that the node search box cannot search, the UI of the search box seems incorrect, very primitive, and the search box still exists when the sidebar is folded. I tried refreshing and disabling cache, but it didn't work. I have no way to solve it. I really need it. It is a very practical plug-in. If this problem is fixed, I will update to the latest version.
![image](https://github.com/user-attachments/assets/2affecdf-ddd7-4ed1-85a3-7c1287de149c)

**Comment by camoody1** [comment] 2024-08-06 03:26
Same with me, man. I uninstalled the custom node and resintalled it and it's still not working. 🤷🏼

**Comment by camoody1** [comment] 2024-08-06 03:58
Okay @Nuked88  ... The sidebar node actually DOES work in a Microsoft Edge "In Private" browser window, but when I try it in my regular window - even with all of my browser extensions disabled - it still doesn't work. Do you have any thoughts on how/why this would happen?

**Comment by Nuked88** [comment] 2024-08-06 05:44
If it's working in private mode, is a cache issue! I'm closing this since is a duplicate of #100

**Closed by Nuked88** 2024-08-06 05:44 UTC
Labels: bug
